// Generated by the protocol buffer compiler to check spring application context starts without errors.
package com.mrxgrc.inventory;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class InventoryApiApplicationTests {

    @Test
    void contextLoads() {
    }

}
